apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: atlassian-bamboo
  name: atlassian-bamboo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: atlassian-bamboo
  template:
    metadata:
      labels:
        app: atlassian-bamboo
    spec:
      containers:
        - name: proxy
          image: gcr.io/google_containers/kubectl:v0.18.0-120-gaeb4ac55ad12b1-dirty 
          args:
            - proxy
            - "-p"
            - "8001"
          imagePullPolicy: Always
        - name: bamboo
          image: jbianquettibitnami/atlassian-bamboo:latest
          imagePullPolicy: Always
          env:
            - name: CLOUDSDK_CONFIG
              value: /var/atlassian/bamboo
          volumeMounts:
          - name: bamboo-workdir
            mountPath: /var/atlassian/bamboo
          - name: bamboo-logs
            mountPath: /opt/atlassian/bamboo/logs
          - name: gcloud-svc-account
            mountPath: /var/lib/kubernetes/gcloud-svc-account
          ports:
          - containerPort: 8085
            name: http
            protocol: TCP
          - containerPort: 54663
            name: ssh
            protocol: TCP
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: http
              scheme: HTTP
            initialDelaySeconds: 120
            periodSeconds: 6
            successThreshold: 1
            timeoutSeconds: 5
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: http
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 3
      volumes:
        - name: bamboo-workdir
          emptyDir: {}
        - name: bamboo-logs
          emptyDir: {}
        - name: gcloud-svc-account
          secret:
            secretName: gcloud-svc-account


