kind: Service
apiVersion: v1
metadata:
  name: atlassian-bamboo
  labels:
    app: atlassian-bamboo
spec:
  selector:
    app: atlassian-bamboo
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8085
  type: LoadBalancer
